NUMPY

class names of numpy is ndarray

Numpy is apython librasry used for working with array

In python we have lists that serves the purpose of array , but they are slow to process.

Numpy aims t o provide an array object that is up to 50 faster thasn traditional python list

The array object in numpy is called ndarray. it provides a lot of supporting functions that makes working with ndarray very easy

Array are very frequently used in datascience , where speed and resource are very important.

Collection of homogenous data

It does not suppirt hetrogenous data.

In [9]:
import numpy as np
x= np.array([1,2,3,4])
print(x)


[1 2 3 4]


In [3]:
import numpy as np
x= np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [4]:
print(type(x))

<class 'numpy.ndarray'>


In [5]:
print(x.ndim)

1


In [6]:
print(x.shape)

(4,)


**2d** **array**

In [7]:
import numpy as np
x=np.array([[1,2,3,4]])
print(x)
print(x.shape)
print(x.ndim)

[[1 2 3 4]]
(1, 4)
2


In [10]:
import numpy as np
x= np.array([[1,2,3,4],[1,2,3,4]])
print(x)
print(x.shape)
print(x.ndim)

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)
2


In [12]:
import numpy as np
x=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(x)
print(x.shape)
print(x.ndim)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
(4, 5)
2


In [14]:
import numpy as np
x= np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(x)
print(x.shape)
print(x.ndim)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
(2, 6)
2


**3d** **array**

group of 2d array compains to form 3d array

In [17]:
x= np.array([[[2,3,4],[7,17,30]],[[2,3,4],[7,17,30]]])
print(x)
print(x.shape)
print(type(x))
print(x.ndim)


[[[ 2  3  4]
  [ 7 17 30]]

 [[ 2  3  4]
  [ 7 17 30]]]
(2, 2, 3)
<class 'numpy.ndarray'>
3


In [18]:
x= np.array([[[1,2],[3,4],[5,6],[7,8]],[[1,2],[3,4],[5,6],[7,8]]])
print(x)
print(x.shape)
print(x.ndim)


[[[1 2]
  [3 4]
  [5 6]
  [7 8]]

 [[1 2]
  [3 4]
  [5 6]
  [7 8]]]
(2, 4, 2)
3


In [20]:
x=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(x)
print(x.shape)
print(x.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
(3, 2, 3)
3


In [22]:
x=np.array([[[1,2],[1,2]],[[1,2],[1,2]],[[1,2],[1,2]],[[1,2],[1,2]]])
print(x)
print(x.shape)
print(x.ndim)

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]

 [[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]
(4, 2, 2)
3


In [26]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
np.zeros((2,3,4),dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [29]:
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [30]:
np.ones((1,2,3),dtype=int)

array([[[1, 1, 1],
        [1, 1, 1]]])

In [31]:
np.arange(20,50,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [33]:
np.linspace(20,80,8) # evenly spaced values

array([20.        , 28.57142857, 37.14285714, 45.71428571, 54.28571429,
       62.85714286, 71.42857143, 80.        ])

In [34]:
np.linspace(20,80)

array([20.        , 21.2244898 , 22.44897959, 23.67346939, 24.89795918,
       26.12244898, 27.34693878, 28.57142857, 29.79591837, 31.02040816,
       32.24489796, 33.46938776, 34.69387755, 35.91836735, 37.14285714,
       38.36734694, 39.59183673, 40.81632653, 42.04081633, 43.26530612,
       44.48979592, 45.71428571, 46.93877551, 48.16326531, 49.3877551 ,
       50.6122449 , 51.83673469, 53.06122449, 54.28571429, 55.51020408,
       56.73469388, 57.95918367, 59.18367347, 60.40816327, 61.63265306,
       62.85714286, 64.08163265, 65.30612245, 66.53061224, 67.75510204,
       68.97959184, 70.20408163, 71.42857143, 72.65306122, 73.87755102,
       75.10204082, 76.32653061, 77.55102041, 78.7755102 , 80.        ])

In [35]:
np.full((2,3),70,dtype=float)

array([[70., 70., 70.],
       [70., 70., 70.]])

In [36]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.random.random((3,4,6))

array([[[0.4246316 , 0.94160013, 0.45378437, 0.70674437, 0.95455884,
         0.08133147],
        [0.14258433, 0.88597776, 0.99048598, 0.07862194, 0.46908423,
         0.27509305],
        [0.65151384, 0.92101116, 0.68581243, 0.61670158, 0.53297194,
         0.60697711],
        [0.19023934, 0.44822257, 0.61549419, 0.90005724, 0.33815197,
         0.88980501]],

       [[0.94468726, 0.27777348, 0.52946286, 0.07147643, 0.8795739 ,
         0.16691134],
        [0.28403377, 0.89290459, 0.58933232, 0.74931962, 0.56591444,
         0.41851034],
        [0.56157324, 0.32857601, 0.81664053, 0.17790654, 0.46450013,
         0.32381529],
        [0.82890094, 0.85023878, 0.4843707 , 0.90676383, 0.2995069 ,
         0.45718627]],

       [[0.80119002, 0.96878621, 0.74923735, 0.24413751, 0.65932784,
         0.45722848],
        [0.19110017, 0.95974779, 0.79225992, 0.43271519, 0.50326961,
         0.42832203],
        [0.24725667, 0.27434976, 0.31585826, 0.32942024, 0.40287665,
         0.813482

In [38]:
np.random.randint(100,200,(2,4,6))

array([[[161, 181, 157, 180, 105, 138],
        [115, 174, 143, 160, 111, 134],
        [141, 145, 137, 131, 103, 140],
        [131, 185, 174, 183, 167, 130]],

       [[106, 115, 194, 135, 152, 121],
        [142, 121, 124, 101, 161, 197],
        [147, 159, 192, 116, 109, 175],
        [189, 134, 193, 174, 128, 116]]])

In [40]:
np.random.randint(100,size=(2,4,6))

array([[[98, 75, 76, 86, 78, 89],
        [82, 77, 78, 92, 14, 88],
        [52, 36, 14, 66, 31, 16],
        [ 3, 73, 71, 31, 14, 62]],

       [[40, 23, 34, 21, 92, 31],
        [59,  4, 45, 78, 38, 77],
        [35, 49, 33, 72, 55, 18],
        [75, 67, 99, 23, 19, 15]]])